version: "3"
services:
    nginx:
        container_name: nginx
        build: requirements/nginx/
        ports:
            - 443:443
        volumes:
            - /home/rvernon/data/wordpress:/var/www/wordpress
        restart: always


    wordpress:
        container_name: wordpress
        volumes:
            - /home/rvernon/data/wordpress:/var/www/wordpress
        build: requirements/wordpress/
        ports:
            - 9000:9000
        restart: always


    mariadb:
        container_name: mariadb
        build: requirements/mariadb/
        ports:
            - 3306:3306
        volumes:
            - /home/rvernon/data/maridb:/var/www/mariadb
        restart: always
