version: "3"
services:
    nginx:
        container_name: nginx
        build: requirements/nginx/
        hostname: rvernon.42.fr
        env_file:
            - ./.env
        ports:
            - 443:443
        environment:
            - VIRTUAL_HOST=whoami.local
        volumes:
            - /home/rvernon/data/wordpress:/var/www/wordpress
        restart: always


    wordpress:
        container_name: wordpress
        volumes:
            - /home/rvernon/data/wordpress:/var/www/wordpress
        build: requirements/wordpress/
        env_file:
            - ./.env
        environment:
              - WORDPRESS_DB_USER=$MYSQL_USER
              - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
              - WORDPRESS_DB_NAME=wordpress
        ports:
            - 9000:9000
        restart: always


    mariadb:
        container_name: mariadb
        env_file:
            - ./.env
        build: requirements/mariadb/
        ports:
            - 3306:3306
        volumes:
            - /home/rvernon/data/maridb:/var/www/mariadb
